### ISSUE TITLE
Missing Files when Compiling

### ISSUE THREAD

**Issue by EdenRidgway** [cloudn1ne/MowgliRover#2]
Thanks for all your work on this project. I've been following the installation instructions on https://github.com/cloudn1ne/MowgliRover/blob/main/help/InstallMowgli.md and it looks like there may be files missing in git. 

When executing catkin_make on my raspberry Pi I get the following (in both the main and test branches):
```
Scanning dependencies of target vesc_msgs_generate_messages_cpp
/home/pi/MowgliRover/src/mowgli/src/mowgli_blade.cpp:16:10: fatal error: mower_msgs/MowerControlSrv.h: No such file or directory
   16 | #include <mower_msgs/MowerControlSrv.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[ 27%] Built target costmap_converter_generate_messages_lisp
```

I have not been able to find the MowerControlSrv.h file or the mower_msgs folder in the repository so maybe it hasn't been added. If however this is meant to be generated as part of the build process, then that that doesn't appear to be happening either unfortunately.

**Comment by cloudn1ne** [comment]
1. ~~Are you trying the main or testing branch ?~~
2. They should be build out of the same ROS pkg (mower_msgs) - can you share your full compile output ? 

cd ~/MowgliRover/
catkin_make --only-pkg-with-deps mower_msgs

**Comment by EdenRidgway** [comment]
Thanks for the quick reply. I cleared out the Mowgli folder and provisioned more swap space. I then did it all from scratch and it worked this time. I wonder if I hadn't provisioned enough swap the first time round or something like that and the compile failed at an earlier stage (before the error message above) and I simply hadn't noticed. Unfortunately my Raspberry Pi 4 only has 2GB of RAM and as you'll know it isn't that easy to get one with more RAM these days.

**Comment by cloudn1ne** [comment]
> 

ack - the only thing i can think of because steve ran into that, are missing dependencies, he build it with -j1 and i build with -j4 so didnt notice such a problem - looks like a missing dependency for the mowgli pkg (mowgli_blade.cpp) towards the openmower_ros/mower_msgs pkg - i'll doublecheck, but worst case a second compile should fix it because then the mower_msgs would have been catched in the first run.
